### ISSUE TITLE
Memory Allocator

### ISSUE THREAD

**Issue by Vitale87** [fred41/ASM#13]
Hi friend41 i followed all your work with the custom memory allocator its a shame you left the community dwarden mentioned you had a privately tested memory allocator newer than the 1 availiable here is their any chance i could get a copy of it for my own personal use it helped increase my fps massively compared to the bi studios 1 sometimes seeing 20 - 30 fps increases it was amazing

I can be contacted vitale1080@hotmail.com

**Comment by fred41** [comment]
Hi Vitale87,
i didn't left the arma community and you posted your comment in the wrong repository ;)

My memory allocator related project is closed since months, there are no plans to continue it soon.

The current stable allocator is based on intels version 4.2 update 2 and runs very well.
Actually you can't get a faster allocator for arma currently. My experimental builds, you mentioned, didn't relly perform better.

Greets,
Fred41
